import type { CriticalCandidate,CriticalRunKind } from './critical';
const required=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required for Gmail delivery.`);return value};
const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const recipients=(mode:string)=>{const key=mode==='test'?'VESTA_EMAIL_TEST_RECIPIENTS':'VESTA_EMAIL_RECIPIENTS';return required(key).split(',').map(x=>x.trim()).filter(Boolean)};

export function renderDigest(kind:CriticalRunKind,candidates:CriticalCandidate[],mode:string,runKey:string){
 const label=kind==='morning-reroutes'?'9:00 AM Reroutes':'2:30 PM Missed Critical Contacts',subject=`[Vesta Critical Actions] ${label} — ${candidates.length} unresolved`;
 const rows=candidates.map(item=>`<tr><td><a href="${escapeHtml(item.fubUrl)}">${escapeHtml(item.leadName)}</a><br><small>${escapeHtml(item.source)} · ${escapeHtml(item.segment)}</small></td><td>${escapeHtml(item.ownerName)}</td><td>${escapeHtml(item.suggestedOwnerName||'—')}</td><td>${item.hoursOverdue.toFixed(1)}h</td><td><b>${escapeHtml(item.recommendation)}</b><br><small>${escapeHtml(item.reason)}</small></td></tr>`).join('');
 const html=`<!doctype html><html><body style="font-family:Arial,sans-serif;color:#1b1a17"><h2>${escapeHtml(label)}</h2><p>${candidates.length} unresolved critical action${candidates.length===1?'':'s'} require management review.</p><table cellpadding="9" cellspacing="0" border="1" style="border-collapse:collapse;border-color:#ddd;width:100%"><thead><tr><th>Lead</th><th>Current owner</th><th>Suggested owner</th><th>Overdue</th><th>Recommended action</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No eligible records.</td></tr>'}</tbody></table><p style="color:#777;font-size:12px">Run ${escapeHtml(runKey)} · Existing Raven/FUB spine · ${escapeHtml(mode)} mode</p></body></html>`;
 const text=[label,`${candidates.length} unresolved critical actions.`,...candidates.map(item=>`${item.leadName} | ${item.ownerName} | ${item.suggestedOwnerName||'No suggested owner'} | ${item.hoursOverdue.toFixed(1)}h overdue | ${item.recommendation} | ${item.fubUrl}`),`Run ${runKey}`].join('\n');
 return {subject,html,text,to:recipients(mode)};
}

async function accessToken(){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:required('GMAIL_CLIENT_ID'),client_secret:required('GMAIL_CLIENT_SECRET'),refresh_token:required('GMAIL_REFRESH_TOKEN'),grant_type:'refresh_token'}),cache:'no-store',signal:AbortSignal.timeout(10000)});const body=await response.json().catch(()=>null) as any;if(!response.ok||!body?.access_token)throw new Error(body?.error_description||'Gmail OAuth token refresh failed.');return String(body.access_token)}
const base64url=(value:string)=>Buffer.from(value).toString('base64url');
export async function sendDigest(message:{subject:string;html:string;text:string;to:string[]}){
 const boundary=`vesta_${Date.now().toString(36)}`,from=required('GMAIL_SENDER_ADDRESS'),mime=[`From: ${from}`,`To: ${message.to.join(', ')}`,`Subject: ${message.subject}`,'MIME-Version: 1.0',`Content-Type: multipart/alternative; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset="UTF-8"','',message.text,`--${boundary}`,'Content-Type: text/html; charset="UTF-8"','',message.html,`--${boundary}--`].join('\r\n');
 const token=await accessToken(),response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({raw:base64url(mime)}),cache:'no-store',signal:AbortSignal.timeout(15000)});const body=await response.json().catch(()=>null) as any;if(!response.ok||!body?.id)throw new Error(body?.error?.message||`Gmail delivery failed (${response.status})`);return {delivered:true,messageId:String(body.id),threadId:body.threadId?String(body.threadId):null,to:message.to};
}
