/** Central-time business clock used by response obligations, including DST. */
const ZONE='America/Chicago',OPEN_HOUR=9,CLOSE_HOUR=17;
const partsFormatter=new Intl.DateTimeFormat('en-US',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'});
const offsetFormatter=new Intl.DateTimeFormat('en-US',{timeZone:ZONE,timeZoneName:'longOffset'});
const parts=(instant:Date)=>Object.fromEntries(partsFormatter.formatToParts(instant).filter(item=>item.type!=='literal').map(item=>[item.type,item.value])) as Record<string,string>;
const key=(year:number,month:number,day:number)=>`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
const holidays=()=>new Set((process.env.VESTA_BUSINESS_HOLIDAYS||process.env.VESTA_BUSINESS_CLOSURES||'').split(',').map(item=>item.trim()).filter(Boolean));
const offsetMinutes=(instant:Date)=>{const label=offsetFormatter.formatToParts(instant).find(item=>item.type==='timeZoneName')?.value||'GMT-06:00',match=label.match(/GMT([+-])(\d{2}):(\d{2})/);if(!match)return -360;return (match[1]==='-'?-1:1)*(Number(match[2])*60+Number(match[3]))};
const centralInstant=(year:number,month:number,day:number,hour:number,minute=0)=>{const probe=new Date(Date.UTC(year,month-1,day,12)),offset=offsetMinutes(probe);return Date.UTC(year,month-1,day,hour,minute)-offset*60000};
const nextDate=(year:number,month:number,day:number)=>{const next=new Date(Date.UTC(year,month-1,day+1));return {year:next.getUTCFullYear(),month:next.getUTCMonth()+1,day:next.getUTCDate()}};
const businessDay=(year:number,month:number,day:number)=>{const instant=new Date(centralInstant(year,month,day,12)),weekday=parts(instant).weekday;return weekday!=='Sat'&&weekday!=='Sun'&&!holidays().has(key(year,month,day))};
export function addCentralBusinessMinutes(value:string|number|Date,minutes:number):number|null{let cursor=new Date(value).getTime();if(!Number.isFinite(cursor)||minutes<0)return null;let local=parts(new Date(cursor)),date={year:Number(local.year),month:Number(local.month),day:Number(local.day)},remaining=minutes;for(let guard=0;guard<370;guard++){const open=centralInstant(date.year,date.month,date.day,OPEN_HOUR),close=centralInstant(date.year,date.month,date.day,CLOSE_HOUR);if(businessDay(date.year,date.month,date.day)){cursor=Math.max(cursor,open);if(cursor<close){const available=Math.floor((close-cursor)/60000);if(remaining<=available)return cursor+remaining*60000;remaining-=available}}date=nextDate(date.year,date.month,date.day);cursor=centralInstant(date.year,date.month,date.day,OPEN_HOUR)}return null}
