import { NormalizedLead, NormalizedTask, NormalizedUser } from '@/lib/domain/types';
const now=Date.now();const iso=(days:number)=>new Date(now-days*86400000).toISOString();
type LeadBase=Omit<NormalizedLead,'assignedUserRole'|'price'|'collaborators'|'ageBand'|'engagementBand'|'cadenceKey'|'cadenceLabel'|'cadenceStatus'|'cadenceDueAt'|'cadenceDaysLate'|'cadenceClearRequired'|'overdueTaskCount'|'responseSlaStatus'|'decisionSnapshotId'|'governanceScore'|'governanceSignals'|'riskLevel'|'riskReasons'|'recommendedAction'|'decision'>;
export const demoUsers:NormalizedUser[]=[
{id:1,name:'Avery Brooks',email:'avery@vesta.demo',role:'Agent',isActive:true},{id:2,name:'Jordan Lee',email:'jordan@vesta.demo',role:'Agent',isActive:true},{id:3,name:'Morgan Reyes',email:'morgan@vesta.demo',role:'Broker',isActive:true,isOwner:true}
];
export const demoLeads:LeadBase[]=[
{id:101,name:'Maya Thompson',stage:'Lead',source:'Website',businessSegment:'buyer-seller',businessSegmentReason:'FUB buyer default',leadLane:'buyer',timeframeId:null,timeframeStatus:null,handRaiseAt:iso(.03),assignedUserId:1,assignedUserName:'Avery Brooks',createdAt:iso(.2),updatedAt:iso(.1),lastActivityAt:iso(.03),lastCommunicationAt:null,nextTaskAt:null,emails:['maya@example.com'],phones:['312-555-0101'],tags:['buyer','west-loop']},
{id:102,name:'Ethan Carter',stage:'Showing Homes',source:'Zillow',businessSegment:'buyer-seller',businessSegmentReason:'FUB buyer default',leadLane:'buyer',timeframeId:null,timeframeStatus:null,handRaiseAt:null,assignedUserId:2,assignedUserName:'Jordan Lee',createdAt:iso(4),updatedAt:iso(1),lastActivityAt:iso(.5),lastCommunicationAt:iso(2),nextTaskAt:iso(-1),emails:['ethan@example.com'],phones:['312-555-0102'],tags:['condo']},
{id:103,name:'Sophia Nguyen',stage:'Nurture',source:'Referral',businessSegment:'buyer-seller',businessSegmentReason:'Confirmed by FUB Seller tag',leadLane:'seller',timeframeId:3,timeframeStatus:'3-6 Months',handRaiseAt:null,assignedUserId:null,assignedUserName:'Unassigned',createdAt:iso(42),updatedAt:iso(8),lastActivityAt:iso(8),lastCommunicationAt:iso(31),nextTaskAt:null,emails:['sophia@example.com'],phones:['312-555-0103'],tags:['seller']},
{id:104,name:'Noah Williams',stage:'Renter',source:'Apartments.com',businessSegment:'rental',businessSegmentReason:'Confirmed by FUB Renter stage',leadLane:'renter',timeframeId:null,timeframeStatus:null,handRaiseAt:null,assignedUserId:1,assignedUserName:'Avery Brooks',createdAt:iso(310),updatedAt:iso(.2),lastActivityAt:iso(.2),lastCommunicationAt:iso(180),nextTaskAt:iso(-3),emails:['noah@example.com'],phones:['312-555-0104'],tags:['reactivated','rental']}
];
export const demoTasks:NormalizedTask[]=[{id:201,personId:102,assignedUserId:2,assignedUserName:'Jordan Lee',name:'Call about showing availability',type:'Call',dueAt:iso(-1),isCompleted:false},{id:202,personId:104,assignedUserId:1,assignedUserName:'Avery Brooks',name:'Review newly viewed listings',type:'Follow Up',dueAt:iso(-3),isCompleted:false}];
